### ISSUE TITLE
State does not change from Opening to Open

### ISSUE THREAD

**Issue by marcodallago** [pfandrade/ha-custom-components#1]
Hi!

Found your post here (https://community.home-assistant.io/t/faking-garage-door-states-like-closing-opening/276691/6).
Thank you very much, you created exactly what I was searching for !!!!

I'm just having one issue, which consist on not changing from Opening to Open. Trigger works great, on/ff, also it correctly closes and changes its state (Closing > Close).

As template for cover I used the same one you posted. I waited a little longer but even after 3 minutes nothing changes.

As default it starts close which is great btw

This is the code

```
cover:
  - platform: pcc
    covers:
      pcc_garage_door:
        friendly_name: "Garage Door"
        value_template: "{{ is_state('binary_sensor.garage_door_sensor', 'on') }}"
        open_cover:
          service: switch.toggle
          data:
            entity_id: switch.garage_door
        close_cover:
          service: switch.toggle
          data:
            entity_id: switch.garage_door
        travelling_time_down: 5
        travelling_time_up: 5
        device_class: "garage"
        unique_id: "pcc_garage_door"
```

Home Assistant is 2021.12.7, I control everything with Homebridge and therefore Homekit
